// Code generated by MockGen. DO NOT EDIT.
// Source: driver/storage.go

// Package mock_driver is a generated GoMock package.
package mock_driver

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStorage is a mock of Storage interface
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockStorage) Get(key, value interface{}) error {
	ret := m.ctrl.Call(m, "Get", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockStorageMockRecorder) Get(key, value interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), key, value)
}

// Set mocks base method
func (m *MockStorage) Set(key, value interface{}) error {
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockStorageMockRecorder) Set(key, value interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStorage)(nil).Set), key, value)
}

// MockDeletableStorage is a mock of DeletableStorage interface
type MockDeletableStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDeletableStorageMockRecorder
}

// MockDeletableStorageMockRecorder is the mock recorder for MockDeletableStorage
type MockDeletableStorageMockRecorder struct {
	mock *MockDeletableStorage
}

// NewMockDeletableStorage creates a new mock instance
func NewMockDeletableStorage(ctrl *gomock.Controller) *MockDeletableStorage {
	mock := &MockDeletableStorage{ctrl: ctrl}
	mock.recorder = &MockDeletableStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeletableStorage) EXPECT() *MockDeletableStorageMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockDeletableStorage) Get(key, value interface{}) error {
	ret := m.ctrl.Call(m, "Get", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockDeletableStorageMockRecorder) Get(key, value interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeletableStorage)(nil).Get), key, value)
}

// Set mocks base method
func (m *MockDeletableStorage) Set(key, value interface{}) error {
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockDeletableStorageMockRecorder) Set(key, value interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockDeletableStorage)(nil).Set), key, value)
}

// Del mocks base method
func (m *MockDeletableStorage) Del(key interface{}) error {
	ret := m.ctrl.Call(m, "Del", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del
func (mr *MockDeletableStorageMockRecorder) Del(key interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockDeletableStorage)(nil).Del), key)
}

// MockClearableStorage is a mock of ClearableStorage interface
type MockClearableStorage struct {
	ctrl     *gomock.Controller
	recorder *MockClearableStorageMockRecorder
}

// MockClearableStorageMockRecorder is the mock recorder for MockClearableStorage
type MockClearableStorageMockRecorder struct {
	mock *MockClearableStorage
}

// NewMockClearableStorage creates a new mock instance
func NewMockClearableStorage(ctrl *gomock.Controller) *MockClearableStorage {
	mock := &MockClearableStorage{ctrl: ctrl}
	mock.recorder = &MockClearableStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClearableStorage) EXPECT() *MockClearableStorageMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockClearableStorage) Get(key, value interface{}) error {
	ret := m.ctrl.Call(m, "Get", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockClearableStorageMockRecorder) Get(key, value interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClearableStorage)(nil).Get), key, value)
}

// Set mocks base method
func (m *MockClearableStorage) Set(key, value interface{}) error {
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockClearableStorageMockRecorder) Set(key, value interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockClearableStorage)(nil).Set), key, value)
}

// Clear mocks base method
func (m *MockClearableStorage) Clear() error {
	ret := m.ctrl.Call(m, "Clear")
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear
func (mr *MockClearableStorageMockRecorder) Clear() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockClearableStorage)(nil).Clear))
}
