// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mock_cachex is a generated GoMock package.
package mock_cachex

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockStorage is a mock of Storage interface
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockStorage) Get(ctx context.Context, key, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockStorageMockRecorder) Get(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), ctx, key, value)
}

// Set mocks base method
func (m *MockStorage) Set(ctx context.Context, key, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockStorageMockRecorder) Set(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStorage)(nil).Set), ctx, key, value)
}

// MockDeletableStorage is a mock of DeletableStorage interface
type MockDeletableStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDeletableStorageMockRecorder
}

// MockDeletableStorageMockRecorder is the mock recorder for MockDeletableStorage
type MockDeletableStorageMockRecorder struct {
	mock *MockDeletableStorage
}

// NewMockDeletableStorage creates a new mock instance
func NewMockDeletableStorage(ctrl *gomock.Controller) *MockDeletableStorage {
	mock := &MockDeletableStorage{ctrl: ctrl}
	mock.recorder = &MockDeletableStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeletableStorage) EXPECT() *MockDeletableStorageMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockDeletableStorage) Get(ctx context.Context, key, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockDeletableStorageMockRecorder) Get(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeletableStorage)(nil).Get), ctx, key, value)
}

// Set mocks base method
func (m *MockDeletableStorage) Set(ctx context.Context, key, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockDeletableStorageMockRecorder) Set(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockDeletableStorage)(nil).Set), ctx, key, value)
}

// Del mocks base method
func (m *MockDeletableStorage) Del(ctx context.Context, keys ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del
func (mr *MockDeletableStorageMockRecorder) Del(ctx interface{}, keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockDeletableStorage)(nil).Del), varargs...)
}

// MockClearableStorage is a mock of ClearableStorage interface
type MockClearableStorage struct {
	ctrl     *gomock.Controller
	recorder *MockClearableStorageMockRecorder
}

// MockClearableStorageMockRecorder is the mock recorder for MockClearableStorage
type MockClearableStorageMockRecorder struct {
	mock *MockClearableStorage
}

// NewMockClearableStorage creates a new mock instance
func NewMockClearableStorage(ctrl *gomock.Controller) *MockClearableStorage {
	mock := &MockClearableStorage{ctrl: ctrl}
	mock.recorder = &MockClearableStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClearableStorage) EXPECT() *MockClearableStorageMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockClearableStorage) Get(ctx context.Context, key, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockClearableStorageMockRecorder) Get(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClearableStorage)(nil).Get), ctx, key, value)
}

// Set mocks base method
func (m *MockClearableStorage) Set(ctx context.Context, key, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockClearableStorageMockRecorder) Set(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockClearableStorage)(nil).Set), ctx, key, value)
}

// Clear mocks base method
func (m *MockClearableStorage) Clear(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear
func (mr *MockClearableStorageMockRecorder) Clear(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockClearableStorage)(nil).Clear), ctx)
}

// MockSetWithTTLableStorage is a mock of SetWithTTLableStorage interface
type MockSetWithTTLableStorage struct {
	ctrl     *gomock.Controller
	recorder *MockSetWithTTLableStorageMockRecorder
}

// MockSetWithTTLableStorageMockRecorder is the mock recorder for MockSetWithTTLableStorage
type MockSetWithTTLableStorageMockRecorder struct {
	mock *MockSetWithTTLableStorage
}

// NewMockSetWithTTLableStorage creates a new mock instance
func NewMockSetWithTTLableStorage(ctrl *gomock.Controller) *MockSetWithTTLableStorage {
	mock := &MockSetWithTTLableStorage{ctrl: ctrl}
	mock.recorder = &MockSetWithTTLableStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSetWithTTLableStorage) EXPECT() *MockSetWithTTLableStorageMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockSetWithTTLableStorage) Get(ctx context.Context, key, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockSetWithTTLableStorageMockRecorder) Get(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSetWithTTLableStorage)(nil).Get), ctx, key, value)
}

// Set mocks base method
func (m *MockSetWithTTLableStorage) Set(ctx context.Context, key, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockSetWithTTLableStorageMockRecorder) Set(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSetWithTTLableStorage)(nil).Set), ctx, key, value)
}

// SetWithTTL mocks base method
func (m *MockSetWithTTLableStorage) SetWithTTL(ctx context.Context, key, value interface{}, TTL time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWithTTL", ctx, key, value, TTL)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWithTTL indicates an expected call of SetWithTTL
func (mr *MockSetWithTTLableStorageMockRecorder) SetWithTTL(ctx, key, value, TTL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWithTTL", reflect.TypeOf((*MockSetWithTTLableStorage)(nil).SetWithTTL), ctx, key, value, TTL)
}
